package io.github.mike10004.vhs.bmp;

import com.google.common.annotations.VisibleForTesting;
import net.lightbody.bmp.mitm.CertificateAndKey;
import net.lightbody.bmp.mitm.CertificateInfo;
import net.lightbody.bmp.mitm.RootCertificateGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nullable;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.security.KeyStore;
import java.security.SecureRandom;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Base64;
import java.util.Date;
import java.util.Random;
import java.util.function.Supplier;

import static com.google.common.base.Preconditions.checkArgument;
import static java.util.Objects.requireNonNull;

public class KeystoreGenerator {

    private static final Logger log = LoggerFactory.getLogger(KeystoreGenerator.class);

    private static final int KEYSTORE_BUFFER_LEN = 8192 * 2;

    static final String KEYSTORE_PRIVATE_KEY_ALIAS = "key";

    /**
     * Enumeration of keystore types. These are just the types supported
     * by these libraries, not all types supported by the JRE.
     */
    public enum KeystoreType {
        PKCS12,
        JKS
    }

    private final Random random;
    private final KeystoreType keystoreType;
    private final MemorySecurityProviderTool securityProviderTool;

    public KeystoreGenerator(KeystoreType keystoreType, MemorySecurityProviderTool securityProviderTool, Random random) {
        this.random = requireNonNull(random);
        this.keystoreType = requireNonNull(keystoreType);
        this.securityProviderTool = requireNonNull(securityProviderTool);
    }

    public KeystoreGenerator(KeystoreType keystoreType) {
        this(keystoreType, new MemorySecurityProviderTool(), new SecureRandom());
    }

    /**
     * Generates keystore data with a new randomly-generated password.
     * @return the keystore data
     * @throws IOException on I/O error
     */
    public KeystoreData generate() throws IOException {
        return generate(null);
    }

    @VisibleForTesting
    static char[] asciiBytesToChars(byte[] asciiBytes) {
        char[] chars = new char[asciiBytes.length];
        for (int i = 0; i < chars.length; i++) {
            checkArgument(asciiBytes[i] >= 0 && asciiBytes[i] < 128, "char at index %s is not ascii: %s", i, asciiBytes[i]);
            chars[i] = (char) asciiBytes[i];
        }
        return chars;
    }

    public KeystoreData generate(@Nullable String certificateCommonName) throws IOException {
        byte[] bytes = new byte[PASSWORD_GENERATION_BYTE_LENGTH];
        random.nextBytes(bytes);
        byte[] asciiBytes = Base64.getEncoder().encode(bytes);
        Arrays.fill(bytes, (byte) 0);
        char[] password = asciiBytesToChars(asciiBytes);
        Arrays.fill(asciiBytes, (byte) 0);
        byte[] keystoreBytes = doGenerate(KEYSTORE_PRIVATE_KEY_ALIAS, password, certificateCommonName);
        return new KeystoreData(keystoreType, keystoreBytes, KEYSTORE_PRIVATE_KEY_ALIAS, password);
    }

    private static final int PASSWORD_GENERATION_BYTE_LENGTH = 32;

    /**
     * Creates a dynamic CA root certificate generator using default settings (2048-bit RSA keys).
     * @return the generator
     */
    protected RootCertificateGenerator buildCertificateGenerator(@Nullable String commonName) {
        if (commonName == null) {
            commonName = getDefaultCommonName();
        }
        long timestamp = System.currentTimeMillis();
        CertificateInfo certificateInfo = new CertificateInfo()
                .commonName(commonName)
                .organization("CA dynamically generated by KeystoreGenerator")
                .notBefore(new Date(timestamp - 365L * 24L * 60L * 60L * 1000L))
                .notAfter(new Date(timestamp + 365L * 24L * 60L * 60L * 1000L));
        RootCertificateGenerator rootCertificateGenerator = RootCertificateGenerator.builder()
                .certificateInfo(certificateInfo)
                .build();
        return rootCertificateGenerator;
    }

    /**
     * Creates a default CN field for a certificate, using the hostname of this machine and the current time.
     */
    private static String getDefaultCommonName() {
        String hostname;
        try {
            hostname = InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException e) {
            hostname = "localhost";
        }

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss zzz");

        String currentDateTime = dateFormat.format(new Date());

        String defaultCN = "Generated CA (" + hostname + ") " + currentDateTime;

        // CN fields can only be 64 characters
        return defaultCN.length() <= 64 ? defaultCN : defaultCN.substring(0, 63);
    }

    protected byte[] doGenerate(String privateKeyAlias, char[] keystorePassword, @Nullable String commonName) throws IOException {
        RootCertificateGenerator rootCertificateGenerator = buildCertificateGenerator(commonName);
        byte[] keystoreBytes = saveRootCertificateAndKey(rootCertificateGenerator.load(),
                privateKeyAlias, keystorePassword);
        log.debug("saved keystore to {}-byte array", keystoreBytes.length);
        return keystoreBytes;
    }

    /**
     * Saves the generated certificate and private key as a file, using the specified password to protect the key store.
     * @param certificateAndKey the root certificate and key
     * @param privateKeyAlias alias for the private key in the KeyStore
     * @param password        password for the private key and the KeyStore
     */
    private byte[] saveRootCertificateAndKey(CertificateAndKey certificateAndKey,
                                          String privateKeyAlias,
                                          char[] password) throws IOException {
        KeyStore keyStore = securityProviderTool.createRootCertificateKeyStore(keystoreType.name(), certificateAndKey, privateKeyAlias, password);
        ByteArrayOutputStream baos = new ByteArrayOutputStream(KEYSTORE_BUFFER_LEN);
        securityProviderTool.saveKeyStore(baos, keyStore, password);
        baos.flush();
        return baos.toByteArray();
    }

    public Supplier<CertificateAndKey> asCertificateAndKeySupplier(@Nullable String certificateCommonName) {
        return () -> {
            try {
                return generate(certificateCommonName).asCertificateAndKeySource().load();
            } catch (IOException e) {
                throw new CertificateGenerationException(e);
            }
        };
    }

    static class CertificateGenerationException extends RuntimeException {
        public CertificateGenerationException(String message) {
            super(message);
        }

        @SuppressWarnings("unused")
        public CertificateGenerationException(String message, Throwable cause) {
            super(message, cause);
        }

        public CertificateGenerationException(Throwable cause) {
            super(cause);
        }
    }
}
